### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by Harshali15** [Gago993/StockPredictionCNN#1]
i am trying to run the code. It shows 'Beginning Stock Prediction..' but it doesnt actually show the graph. What should i do?

**Comment by gognjanovski** [comment]
Hi @Harshali15 ,

It should be simple. 
1. Open the index.html file in google chrome
2. Enter the symbol in input field ex. GOOGL
3. Press the  magnifying glass (button)

If you don't get any results after this steps. Please open the console, see if there is some errors and report them here.

**Comment by gognjanovski** [comment]
I'm closing this issue.
