### ISSUE TITLE
Predict next 7 days

### ISSUE THREAD

**Issue by guillezc** [Gago993/StockPredictionCNN#2]
How i can implement your code for get next 7 days? Any help?

**Comment by gognjanovski** [comment]
Hi @guillezc ,

I was also thinking about this feature. Probably for start what I would do is some function that repeat the process of: 
1. Define array of stock prices from the last 7 days.
2. Predicting for the next day based on last 7 days (defined array)
3. Then add predicted stock price value at the end of the array and remove the first element from the array
4. Then repeat the process 2 again. You can repeat this for 7 times you will get next 7 days prediction

I would probably work on this too in future.
