### ISSUE TITLE
Using with react

### ISSUE THREAD

**Issue by sudharsangs** [Gago993/StockPredictionCNN#3]
How can create this app with react?

**Comment by gognjanovski** [comment]
@sudharsangs Hope this can help you.

1. https://github.com/tensorflow/tfjs#via-npm

Another example of import:

`import * as tf from '@tensorflow/tfjs';
// Definition of the component supporting the model
// ...
protected async loadModel() {
    this.model = await tf.loadModel(AppSettings.mnistModelUrl);
}`

**Comment by sudharsangs** [comment]
Thank You @Gago993

**Comment by gognjanovski** [comment]
Welcome
